@startuml UML_Imagen
hide empty methods
hide empty fields

class AppExpendedor {
  {method} {static} + main(String[]) : void
}

interface Observador

class Controlador

package "modelos" {
  class Expendedor {
    {field} - CAPACIDAD : int
    {field} - primerNumSerie : int
    {method} + getVuelto() : Moneda
    {method} + comprarProducto(Moneda, Catalogo) : Producto
    {method} + rellenar() : void
    {method} + getDepositoProducto(Catalogo) : Deposito<Producto>
    {method} + getDepositosProducto() : ArrayList<Deposito<Producto>>
    {metohd} + getDepVuelto() : Deposito<Moneda>
    {method} + peekVuelto() : Moneda[]
    {method} + getCompra() : Producto
    {method} + peekCompra() : Producto
  }
  class Deposito<T> {
      {method} + addObjeto(T) : void 
      {method} + getObjeto() : T
      {method} + cuantosObjetos() : int
      {method} + peekObjeto(int) : T
  }
  abstract Moneda implements Comparable {
    {method} {abstract} + getValor() : int
    {method} + getSerie() : String
  }
  abstract Producto {
      {field} - serie : String
      {method} {abstract} + consumir() : String
      {method} + getSerie() : String
  }
  abstract Bebida {
  }
  abstract Dulce {
  }
  enum Catalogo {
      {field} - precio : int
      {field} - tipo : Class
      {field} - nombre : String
      {field} - pathSprite : String
      {method} + getPrecio() : int
      {method} + precioAsString() : String
      {method} + setPrecio(int) : void
      {method} + getTipo() : Class
      {method} + getNombre() : String
      {method} + getPathSprite() : String
      {method} {static} + getAllNombres() : String[]
      {method} {static} + matchNombre(String) : Catalogo
      {method} {static} + matchTipo(Class) : Catalogo
      {method} + newInstance(String) : Producto
  }
  enum EnumMoneda {
    {field} - valor : int
    {field} - tipo : Class
    {field} - nombre : String
    {method} + getValor() : int
    {method} + getNombre() : String
    {method} {static} + getAllNombres() : String[]
    {method} {static} + matchNombre(String) : EnumMoneda
    {method} + newInstance() : Moneda
  }

  class Moneda1500
  class Moneda1000
  class Moneda500
  class Moneda100

  class CocaCola
  class Sprite
  class Fanta

  class Snickers
  class Super8
}

package "vistas" {
  class VentanaApp 
  class PanelPrincipal 
  class PanelExpendedor 
  class PanelDeposito 
  class PanelProducto 
  class PanelMoneda 
  class PanelBotones 
  class PanelRetiro 
  class PanelRetiroProducto 
  class PanelRetiroVuelto
}

package "Swing" {
  class JFrame
  class JPanel
  class JButton
  class JRadioButton
  class ButtonGroup
}

' Dependencias
Expendedor ..> Producto
Expendedor ..> Moneda
Expendedor ..> Catalogo

PanelBotones ..> EnumMoneda
PanelBotones ..> Moneda
PanelBotones ..> Catalogo

PanelRetiroVuelto ..> Moneda
PanelRetiroProducto ..> Producto

PanelExpendedor ..> Controlador
PanelBotones ..> Controlador
PanelRetiroVuelto ..> Controlador
PanelRetiro ..> Controlador

' Asociaciones y Agregaciones
Expendedor o-- Deposito
Expendedor o-- Producto

AppExpendedor o-- Expendedor
VentanaApp o-- PanelPrincipal

PanelPrincipal o-- PanelExpendedor
PanelPrincipal o-- PanelBotones

PanelExpendedor o-- Expendedor
PanelExpendedor o-- PanelDeposito

PanelBotones o-- PanelMoneda
PanelBotones o-- PanelRetiro

PanelRetiroVuelto o-- PanelMoneda
PanelRetiroProducto o-- PanelProducto

PanelDeposito o-- PanelMoneda
PanelDeposito o-- PanelProducto

PanelMoneda o-- Moneda
PanelProducto o-- Producto
PanelDeposito o-- Deposito


' Composiciones
AppExpendedor *-- VentanaApp

Controlador *-- PanelRetiro
Controlador *-- PanelExpendedor
Controlador *-- Expendedor

PanelRetiro *-- PanelRetiroProducto
PanelRetiro *-- PanelRetiroVuelto

' Herencias Producto
Producto <|-- Bebida
Producto <|-- Dulce
Bebida <|-- CocaCola
Bebida <|-- Sprite
Bebida <|-- Fanta 
Dulce <|-- Snickers
Dulce <|-- Super8

' Herencias Moneda
Moneda <|-- Moneda100
Moneda <|-- Moneda500
Moneda <|-- Moneda1000
Moneda <|-- Moneda1500

' Implementaciones
Observador <|.. PanelExpendedor
Observador <|.. PanelRetiro
Observador <|.. PanelRetiroProducto
Observador <|.. PanelRetiroVuelto

' Swing
JFrame <|-- VentanaApp
JPanel <|-- PanelPrincipal

JPanel <|-- PanelExpendedor
PanelExpendedor o-- JButton

JPanel <|-- PanelBotones
PanelBotones o-- JButton
PanelBotones o-- JRadioButton
PanelBotones o-- ButtonGroup

JPanel <|-- PanelRetiro
JPanel <|-- PanelRetiroProducto
JPanel <|-- PanelRetiroVuelto
PanelRetiroVuelto o-- JButton
PanelRetiroProducto o-- JButton

JPanel <|-- PanelMoneda
JPanel <|-- PanelProducto
JPanel <|-- PanelDeposito

@enduml
